#!/bin/sh -v

pushd .
cd ../..

CPSUtil/docbuilder/build_cps_doc.py --html -x CPSUtil/docbuilder/doc_directories.xml
CPSUtil/docbuilder/build_cps_doc.py -i --html -x CPSUtil/docbuilder/doc_directories.xml
CPSUtil/docbuilder/build_cps_doc.py -g cps_docs.tar.gz --dist-include="html" \
    -x CPSUtil/docbuilder/doc_directories.xml

popd